### ISSUE TITLE
Botão Visualizar submissão

### ISSUE THREAD

**Issue by JandersonCRB** [thehuxley/thehuxley#1]
Grupos >> Submissões >> Visualizar Submissão

botão com o desenho de lupa não funciona

**Comment by romariorop** [comment]
Isso tb aconteceu comigo para as questões em c++, as questões em c tão funcionando normal

**Comment by r0drigopaes** [comment]
@romariorop , ao invés de ficar aí dizendo que tbm aconteceu com vc, que tal meter a mão na massa e consertar os bugs?
:-)

**Comment by romariorop** [comment]
Feito! vai no proximo merge.
