### ISSUE TITLE
[Alta prioridade] Criação de questionário não tem o campo de hora

### ISSUE THREAD

**Issue by r0drigopaes** [thehuxley/thehuxley#11]
O questionário é usado para provas, e, portanto, é fundamental ter o horário de inicio e de fim. Atualmente existe apenas a data

**Comment by r0drigopaes** [comment]
Tem que formatar melhor no campo de texto, aquele formato tá muito técnico

**Comment by marcioaug** [comment]
r0drigopaes/huxley-web#206
r0drigopaes/huxley-web#204
