### ISSUE TITLE
Criação de questionário, depois que escolhe o problema, tá faltando um botão de concluído

### ISSUE THREAD

**Issue by r0drigopaes** [thehuxley/thehuxley#15]
A pessoa fica na página, escolhe os problemas e não sabe se salvou ou não

**Comment by marcioaug** [comment]
Escolhe o problema? Não seria a criação do questionário?

**Comment by marcioaug** [comment]
Como não é necessário enviar um formulário ou algo do tipo, não há um botão de concluído já que todas as alterações estão sendo salvas no momento em que elas são feitas. 
Vamos colocar um aviso todas as vezes que o questionário salvar uma modificação, no estilo Google Drive.

**Comment by r0drigopaes** [comment]
Isso, criação de questionário. Corrigindo
