### ISSUE TITLE
Estatísticas estão erradas

### ISSUE THREAD

**Issue by r0drigopaes** [thehuxley/thehuxley#17]
Nesse questionário, existem várias submissões, afinal os alunos possuem notas.
Entretanto as estatísticas estão zeradas.

http://dev.thehuxley.com/quiz/705/stats

**Comment by marcioaug** [comment]
Os gráficos estão considerando apenas as submissões feitas durante o tempo que o questionário permaneceu aberto. Se os alunos solucionaram os problemas antes do início do questionário, acontece o que foi relatado.
