### ISSUE TITLE
Nas respostas erradas, tá faltando mostrar de fato a entrada e saída

### ISSUE THREAD

**Issue by r0drigopaes** [thehuxley/thehuxley#18]
http://dev.thehuxley.com/group/165/submission/276994

![the huxley 2015-06-06 14-31-48](https://cloud.githubusercontent.com/assets/1094830/8020683/c97fce4c-0c58-11e5-883f-c3bba85b43c7.png)

**Comment by luizpaulobarroca** [comment]
resolvido, em breve no ar.
