### ISSUE TITLE
Problema não apresenta descrição

### ISSUE THREAD

**Issue by JandersonCRB** [thehuxley/thehuxley#2]
http://dev.thehuxley.com/problem/267

Problema não apresenta descrição, exemplo de entrada nem exemplo de saída.

http://puu.sh/ibuM0/37c82d5dc1.png

**Comment by romariorop** [comment]
Isso acontece porque você possui uma conta de monitor e o problema ainda não foi aprovado, esse problema não aparece na lista de problemas dos alunos
