### ISSUE TITLE
Alteração de dados do perfil não funcionam

### ISSUE THREAD

**Issue by r0drigopaes** [thehuxley/thehuxley#20]
Mudei o nome, cliquei em enviar dados. O nome em cima não alterou. Depois fui de novo para a configuração e o nome ainda estava o antigo e não o novo.

![the huxley 2015-06-06 14-36-01](https://cloud.githubusercontent.com/assets/1094830/8020701/5f954fce-0c59-11e5-95cd-d9c6ff3f2af0.png)

**Comment by luizpaulobarroca** [comment]
Não consegui reproduzir o erro.

**Comment by marcioaug** [comment]
@r0drigopaes teste novamente e reabra a issue se necessário.
