### ISSUE TITLE
Code not found ao tentar visualizar uma submissão

### ISSUE THREAD

**Issue by r0drigopaes** [thehuxley/thehuxley#21]
http://dev.thehuxley.com/group/119/submission/222921

![the huxley 2015-06-06 14-37-17](https://cloud.githubusercontent.com/assets/1094830/8020703/8c546b4e-0c59-11e5-90c1-9f6e079aca7e.png)

**Comment by marcioaug** [comment]
Esta acontecendo para todas as submissões em C++.

**Comment by diogocabral** [comment]
Foi resolvido na issue #164.

**Comment by diogocabral** [comment]
@marcioaug, não consegui colocar o label de done.
