### ISSUE TITLE
Não avaliou uma submissão em Java

### ISSUE THREAD

**Issue by r0drigopaes** [thehuxley/thehuxley#22]
http://dev.thehuxley.com/problem/35/show-solution.
Autenticado como admin.

![the huxley 2015-06-06 14-41-34](https://cloud.githubusercontent.com/assets/1094830/8020720/27ef2a12-0c5a-11e5-8b71-7a88043a0849.png)

**Comment by r0drigopaes** [comment]
Na verdade, o avaliador parece não estar online

**Comment by diogocabral** [comment]
Submissão foi avaliada. Aconteceu um erro no método triggersAfterUpdate do SubmissionService. Vou conversar com o Márcio sobre esse método.

**Comment by diogocabral** [comment]
Não consegui reproduzir o erro. Apaguei a fila e reiniciei o rest, voltou a funcionar.

**Comment by marcioaug** [comment]
@r0drigopaes teste novamente e reabra a issue se o erro voltar a acontecer.
