### ISSUE TITLE
Como eu faço para buscar uma submissão de um determinado aluno?

### ISSUE THREAD

**Issue by r0drigopaes** [thehuxley/thehuxley#23]
Parece que o único caminho atualmente é pelo grupo.  Não fica muito prático.

**Comment by marcioaug** [comment]
Na lista de submissões há apenas as submissões feitas pelo o usuário autenticado. Mostrar as submissões dos alunos na mesma lista fica confuso. Também aumenta a quantidade de parametros no filtro, prejudicando a usabilidade. Mostrar as submissões dos alunos do grupo dentro do contexto do grupo é mais organizado e intuitivo.
