### ISSUE TITLE
Hora do servidor não está no padrão 24 hs

### ISSUE THREAD

**Issue by r0drigopaes** [thehuxley/thehuxley#24]
Submeti as 14:40 e não as 2:40

![the huxley 2015-06-06 14-43-41](https://cloud.githubusercontent.com/assets/1094830/8020732/781e5bde-0c5a-11e5-8e47-d82a9c2ce1a6.png)

**Comment by romariorop** [comment]
feito.. , ainda n posso fechar a issue.
