### ISSUE TITLE
Tá faltando a opção de reavaliar submissões (ou uma submissão individualmente)

### ISSUE THREAD

**Issue by r0drigopaes** [thehuxley/thehuxley#25]

**Comment by diogocabral** [comment]
Onde o botão de reavaliar deve ficar?

Temos três opções, reavaliar uma submissão específica, reavaliar submissões de um problema e reavaliar todas as submissões. As duas últimas opções possuem parâmetros customizáveis, como por exemplo evaluation e submission date.

@r0drigopaes @marcioaug @RomeroMalaquias

**Comment by r0drigopaes** [comment]
@diogocabral , as duas primeiras são mais importantes.
A terceira, também é interessante para os casos onde tivermos algum problema. Nesse caso, o interessante é colocar um filtro por data de início e fim.

**Comment by marcioaug** [comment]
@diogocabral, tem outra issue para criar as ações na view. r0drigopaes/huxley-web#167 destinada ao @romariorop.
