### ISSUE TITLE
Tá faltando tooltip em um dos símbolos da avaliação

### ISSUE THREAD

**Issue by r0drigopaes** [thehuxley/thehuxley#26]
aproveitem para revisar os demais

![the huxley 2015-06-06 14-47-47](https://cloud.githubusercontent.com/assets/1094830/8020745/0f6377c2-0c5b-11e5-82b1-56da1cbcee5d.png)

**Comment by luizpaulobarroca** [comment]
Popover colocado, em breve estará no ar.
