### ISSUE TITLE
Ficou tudo desformatado ao exibir a saida

### ISSUE THREAD

**Issue by r0drigopaes** [thehuxley/thehuxley#27]
http://dev.thehuxley.com/problem/20/submission/276776

![the huxley 2015-06-06 14-50-00](https://cloud.githubusercontent.com/assets/1094830/8020759/5d7a0b9c-0c5b-11e5-9f00-3d54fa97f0b6.png)

**Comment by luizpaulobarroca** [comment]
Corrigido, irá ao ar no próximo merge
