### ISSUE TITLE
Questionário recém-criado não aparece na listagem do aluno

### ISSUE THREAD

**Issue by r0drigopaes** [thehuxley/thehuxley#42]
1- Aluno Rodrigo Paes faz parte do grupo: grupo de uma pessoa só
2- Foi criado um questionário nesse grupo: 

![the huxley 2015-06-18 15-03-39](https://cloud.githubusercontent.com/assets/1094830/8238324/3a62e844-15cb-11e5-9c35-02cabd3d5bac.png)

Perceba que o status do questionário está estranho, pois ele diz que começou 15 horas atrás, termina em 9hs mas está sendo considerado como fechado.

3- Ao acessar o menu questionários (http://dev.thehuxley.com/quizzes?sort=title&order=asc&page=1), esse questionário não aparece.

**Comment by r0drigopaes** [comment]
E pra completar, ao tentar clicar no questionário (http://dev.thehuxley.com/quiz/770)
Ele mostra:
![the huxley 2015-06-18 15-06-08](https://cloud.githubusercontent.com/assets/1094830/8238367/91c84bb0-15cb-11e5-8108-cd0fe1bc3711.png)

**Comment by marcioaug** [comment]
Fixed. commit 6c7db43ffc455c652d3ee0785b3430c204ab19c0 by @diogocabral

**Comment by marcioaug** [comment]
Duplicado em #55

**Comment by marcioaug** [comment]
r0drigopaes/huxley-rest#189

**Comment by diogocabral** [comment]
Fixed. commit 7fdc94865b9b3d8023a6b9304537fb8054a80cbe
