### ISSUE TITLE
Lista de submissões não está paginando

### ISSUE THREAD

**Issue by r0drigopaes** [thehuxley/thehuxley#45]
Ao clicar nos números da página, as submissões são sempre as mesmas

http://dev.thehuxley.com/submissions?sort=submissionDate&order=desc&page=1

**Comment by diogocabral** [comment]
@marcioaug ou @r0drigopaes, passem essa issue pra mim.

**Comment by diogocabral** [comment]
Fixed. commit 949aded198078d0be89e59d07f52f7fcdfdd7ef9
