### ISSUE TITLE
tela de visualizar submissão de um problema desalinhada

### ISSUE THREAD

**Issue by r0drigopaes** [thehuxley/thehuxley#47]
Usando o safari

![captura de tela 2015-06-20 as 13 04 19](https://cloud.githubusercontent.com/assets/1094830/8268077/d7e4cf8c-174d-11e5-9d3b-9cdcc4eac9af.png)

**Comment by marcioaug** [comment]
@rodrigo, testei no chrome e firefox. Testa no safari e fecha a issue por favor.

**Comment by r0drigopaes** [comment]
@marcioaug Não dá pra testar. Não consigo chegar na tela, os botões de visualizar submissão não estão funcionando.

**Comment by r0drigopaes** [comment]
certinho agora.
