### ISSUE TITLE
Nada nesse filtro de questionário funciona

### ISSUE THREAD

**Issue by r0drigopaes** [thehuxley/thehuxley#48]
![captura de tela 2015-06-21 as 17 35 37](https://cloud.githubusercontent.com/assets/1094830/8273271/4d5ce62a-183c-11e5-97c1-70255e3b1941.png)

**Comment by diogocabral** [comment]
@marcioaug ou @r0drigopaes, passem essa issue pra mim.

**Comment by diogocabral** [comment]
Done. commit 14f5aa90eff9f6681881be451ecba4d59be8f58f
