### ISSUE TITLE
Não estão aparecendo todos os questionários

### ISSUE THREAD

**Issue by r0drigopaes** [thehuxley/thehuxley#49]
Estou como o usuário de professor.
Só aparecem 10 questionários.
A paginação não aparece.

**Comment by diogocabral** [comment]
@marcioaug ou @r0drigopaes, passem essa issue pra mim.

**Comment by diogocabral** [comment]
@r0drigopaes, qual o usuário que você está utilizando?

O usuário professor rodrigo/barros possui exatamente 10 questionários.

select count(*) as y0_ from questionnaire_user this_ inner join questionnaire questionna1_ on this_.questionnaire_id=questionna1_.id where this_.user_id=41 and ((1=1));

**Comment by r0drigopaes** [comment]
Oi Diogo, estranho. Dê uma olhada em produção. Veja que esse usuário tem muito mais questionários.
Como a base foi migrada, ele deveria ter mais,

**Comment by diogocabral** [comment]
A tabela questionnaire_user não existe em produção. Fiz uma adaptação para a tabela shiro_user_questionnaire e não retornou nada.

select count(*) as y0_ from shiro_user_questionnaire this_ inner join questionnaire questionna1_ on this_.questionnaire_id=questionna1_.id where this_.shiro_user_id=41 and ((1=1));

@marcioaug, você pode nos dar alguma luz?

**Comment by r0drigopaes** [comment]
e aí?

**Comment by diogocabral** [comment]
Foi resolvido em outra issue.

**Comment by diogocabral** [comment]
Foi resolvido em outra issue.

**Comment by r0drigopaes** [comment]
Foi nada. Continua com o mesmo problema. Só mostra 10 questionários.

**Comment by diogocabral** [comment]
@r0drigopaes, essa issue deve ser marcada como won't fix?
