### ISSUE TITLE
Adicionar monitor em grupo não funciona

### ISSUE THREAD

**Issue by r0drigopaes** [thehuxley/thehuxley#50]
Ao digitar o nome de um usuário, nenhuma lista vem como resposta

**Comment by luizpaulobarroca** [comment]
@r0drigopaes a conta do usuário digitado é um conta de monitor?

**Comment by r0drigopaes** [comment]
@luizpaulobarroca , era um aluno ... e como é uma conta de monitor?

**Comment by romariorop** [comment]
@marcioaug mudei aqui para buscar qualquer aluno e adicionalo como monitor,
esta sendo enviado um post para: http://dev.thehuxley.com:8080/api/groups/149/users/add
com os parametros {users: [{id: 2153, role: "TEACHER_ASSISTANT"}]}
o post está com status ok mas não atualiza o grupo
