### ISSUE TITLE
Links dos questionários não levam a lugar nenhum

### ISSUE THREAD

**Issue by r0drigopaes** [thehuxley/thehuxley#51]
Entrar como aluno.
![captura de tela 2015-06-21 as 18 06 25](https://cloud.githubusercontent.com/assets/1094830/8273357/45480984-1840-11e5-975c-5fe822bbfb18.png)

**Comment by romariorop** [comment]
qual navegador? e usuário? aqui funcionou normal

**Comment by luizpaulobarroca** [comment]
@romariorop você tentou com o usuario do rodrigo aluno? Acredito que não temos esses questionários no banco. O GET no link dos questionários, na conta do rodrigo aluno, estão dando 403.

**Comment by r0drigopaes** [comment]
@romariorop entre como aluno e tente clicar nos links da página inicial .. não funciona.
Estou utilizando o chrome no windows.

**Comment by romariorop** [comment]
@luizpaulobarroca realmente, eu consegui reproduzir logado com o usuário rodrigo aluno, vou verificar com o Marcio se esses questionários estão no banco
