### ISSUE TITLE
Questionário: nenhuma mensagem ao clicar no botão salvar

### ISSUE THREAD

**Issue by r0drigopaes** [thehuxley/thehuxley#52]
![captura de tela 2015-06-21 as 18 07 58](https://cloud.githubusercontent.com/assets/1094830/8273366/7fdefae4-1840-11e5-833f-05ae31f12418.png)

**Comment by marcioaug** [comment]
@rodrigo, testei no chrome e firefox. Testa no safari e fecha a issue por favor.

**Comment by r0drigopaes** [comment]
A mensagem aparece e some tão rápido que não dá pra ver.
Usar a mesma lógica de mensagens da adição de problemas no questionário
