### ISSUE TITLE
ao fazer login como aluno, a página inicial vem vazia

### ISSUE THREAD

**Issue by r0drigopaes** [thehuxley/thehuxley#53]
![captura de tela 2015-06-21 as 18 11 14](https://cloud.githubusercontent.com/assets/1094830/8273372/eccf5856-1840-11e5-8cb6-9a9ef8b647c0.png)

**Comment by romariorop** [comment]
@r0drigopaes estava logado com outra conta antes em algum link especifico? eu não consegui reproduzir esse erro aqui tentando logar como aluno na pagina inicial

**Comment by r0drigopaes** [comment]
@romariorop é ... tbm não consegui mais reproduzir .. marcando como inválido e fechando.
