### ISSUE TITLE
404 - ao clicar em questionário

### ISSUE THREAD

**Issue by r0drigopaes** [thehuxley/thehuxley#55]
![captura de tela 2015-06-21 as 18 13 42](https://cloud.githubusercontent.com/assets/1094830/8273381/45655538-1841-11e5-8321-cd07027e2963.png)

**Comment by diogocabral** [comment]
@marcioaug ou @r0drigopaes, passem essa issue pra mim.

**Comment by diogocabral** [comment]
@r0drigopaes, preciso de mais informações. Não consegui reproduzir. Logado como administrador, consegui acessar os questionários dos grupos que estavam em dev.

**Comment by r0drigopaes** [comment]
Agora apareceu!
Acho que tinha alguma coisa off quando eu tentei. Vou marcar como inválido

**Comment by r0drigopaes** [comment]
Ahá .. descobri. Entre como aluno:
paes

Vá em grupos, dentro do grupo de uma pessoa só tem um questionário. Clique nele.

**Comment by diogocabral** [comment]
@r0drigopaes, passe as credenciais do aluno que você está utilizando.

**Comment by diogocabral** [comment]
@r0drigopaes, estranho que só este questionário que está com problemas. Ele foi criado diretamente no banco?

Está retornando 404 quando na URL http://dev.thehuxley.com:8080/api/quizzes/770/users/53 que retorna o usuário 53 daquele questionário.

A query "select \* from questionnaire_user where questionnaire_id = 770 and user_id = 53; " não retorna nada. Ou seja, tá correto.

**Comment by r0drigopaes** [comment]
não. foi criado pela interface

**Comment by diogocabral** [comment]
Então o bug deve estar na criação do questionário, pois não está adicionando os membros do grupo na tabela questionnaire_user. Vou verificar.

**Comment by diogocabral** [comment]
@r0drigopaes, esse usuário foi adicionado ao grupo após a criação do questionário?

No método save da classe QuestionnaireService os usuários são adicionados, não sei se há sincronia após. Não seria mais interessante que todos os usuários do grupo tivessem acesso aos questionários?

**Comment by diogocabral** [comment]
O que achas, @marcioaug ?

**Comment by marcioaug** [comment]
Provavelmente não foi criado um QuestionnaireUser quando ele entrou no grupo

**Comment by r0drigopaes** [comment]
@diogocabral não lembro. Mas acho que o usuário já existia. Mas de qualquer forma, mesmo que ele não existisse no grupo, a partir do momento que ele entra no grupo, tem que ter acesso ao questionário.

**Comment by diogocabral** [comment]
Então, @r0drigopaes, o meu ponto é: pq temos uma tabela que faz vínculo do questionário com o usuário se todos do grupo devem acessar o questionário?

Pelo que entendi, há uma tabela que faz o vínculo usuário grupo e outra usuário questionário.

**Comment by r0drigopaes** [comment]
Entendi .. pergunte ao @marcioaug e ao @RomeroMalaquias , eles devem saber ... se não fizer sentido, tire.

**Comment by diogocabral** [comment]
Vou mandar msg pelo talk e por aqui.

E aí, @marcioaug e @RomeroMalaquias? Tem alguma justificativa que não levei em conta ou devo proceder e retirar esse relacionamento?

**Comment by marcioaug** [comment]
@diogocabral 
https://github.com/r0drigopaes/huxley-rest/blob/master/grails-app/services/com/thehuxley/GroupService.groovy

Ta faltando uma negação na linha 103, no if.

**Comment by diogocabral** [comment]
Fixed. commit 6c7db43ffc455c652d3ee0785b3430c204ab19c0

**Comment by marcioaug** [comment]
Duplicado #42

**Comment by marcioaug** [comment]
@diogocabral, fiz outra cagada daquelas:

https://github.com/r0drigopaes/huxley-rest/blob/master/grails-app/services/com/thehuxley/QuestionnaireService.groovy

```groovy
UserGroup.findAllByGroupAndRole(questionnaire.group, UserGroup.Role.STUDENT).each {
    if (QuestionnaireUser.findByUserAndQuestionnaire(it.user, questionnaire)) {
        new QuestionnaireUser(questionnaire: questionnaire, user: it.user).save()
    }
 }
```
linha 53, outra negação faltando. Acho que a exclamação do meu teclado ta quebrada. :)
Você arruma @diogocabral, acho que depois disso vai funcionar @romariorop.
